services:
  web:
    build:
      context: ./alx_travel_app
      dockerfile: Dockerfile
    container_name: travel_web
    ports:
      - "8000:8000"
    volumes:
      - ./alx_travel_app:/app
    environment:
      DB_NAME: travel
      DB_USER: traveluser
      DB_PASSWORD: travelpass
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: travel_db
    environment:
      POSTGRES_DB: travel
      POSTGRES_USER: traveluser
      POSTGRES_PASSWORD: travelpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
